### ISSUE TITLE
test

### ISSUE THREAD

**Issue by amanmahendra00** [booboo8499/h1poc-boobalan123#1]
test

**Comment by booboo8499** [comment]
Are you developer or security team of ticketmaster.com?

**Comment by amanmahendra00** [comment]
Please be advised that I am currently engaged as a third party auditor and am neither a developer nor a member of the security team. As part of my auditing duties, I have been requested by the security team to contact the individual who has taken control of a certain subdomain and request that they release it immediately.

I would like to urge you to kindly consider releasing the subdomain in question due to the operational issues that have arisen as a result of its current state of control. Your prompt attention and cooperation in this matter would be greatly appreciated.

Thank you for your attention to this matter.

Aman Mahendra

**Comment by amanmahendra00** [comment]
I would like to compensate you for this takeover please share you PayPal address.

**Comment by booboo8499** [comment]
paypal id:
boobalan1000@gmail.com

**Comment by booboo8499** [comment]
Hi,
I released the domain it will redirect to default page.

**Comment by booboo8499** [comment]
I completely removed the subdomain.kindly check this issue.
